// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:f2cb3027-6ca8-4cec-9abd-dd8457e19a54',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'awsmobileproject-hosting-mobilehub-938654903',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3k8napa8x7eu4.cloudfront.net',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': '6c846105e7e246b3bca4104fafea89d0',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'f7c3b30c-9959-4153-91f7-917c2534e7fb',
    'aws_project_name': 'aws-mobile-project',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'awsmobileproject-mobilehub-938654903',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_TXoyCjSO4',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '409pvcggacpa856ms47o1s3js7',
}

export default awsmobile;
